// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg
{
    /// <summary>
    /// Configures a Frontegg allowed origin.
    /// </summary>
    [FronteggResourceType("frontegg:index/allowedOrigin:AllowedOrigin")]
    public partial class AllowedOrigin : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The allowed origin URI.
        /// </summary>
        [Output("allowedOrigin")]
        public Output<string> origin { get; private set; } = null!;


        /// <summary>
        /// Create a AllowedOrigin resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public AllowedOrigin(string name, AllowedOriginArgs args, CustomResourceOptions? options = null)
            : base("frontegg:index/allowedOrigin:AllowedOrigin", name, args ?? new AllowedOriginArgs(), MakeResourceOptions(options, ""))
        {
        }

        private AllowedOrigin(string name, Input<string> id, AllowedOriginState? state = null, CustomResourceOptions? options = null)
            : base("frontegg:index/allowedOrigin:AllowedOrigin", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing AllowedOrigin resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static AllowedOrigin Get(string name, Input<string> id, AllowedOriginState? state = null, CustomResourceOptions? options = null)
        {
            return new AllowedOrigin(name, id, state, options);
        }
    }

    public sealed class AllowedOriginArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The allowed origin URI.
        /// </summary>
        [Input("allowedOrigin", required: true)]
        public Input<string> origin { get; set; } = null!;

        public AllowedOriginArgs()
        {
        }
        public static new AllowedOriginArgs Empty => new AllowedOriginArgs();
    }

    public sealed class AllowedOriginState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The allowed origin URI.
        /// </summary>
        [Input("allowedOrigin")]
        public Input<string>? origin { get; set; }

        public AllowedOriginState()
        {
        }
        public static new AllowedOriginState Empty => new AllowedOriginState();
    }
}
