// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg
{
    /// <summary>
    /// Configures a Frontegg user.
    /// </summary>
    [FronteggResourceType("frontegg:index/user:User")]
    public partial class User : global::Pulumi.CustomResource
    {
        /// <summary>
        /// Whether the user gets verified upon creation.
        /// </summary>
        [Output("automaticallyVerify")]
        public Output<bool?> AutomaticallyVerify { get; private set; } = null!;

        /// <summary>
        /// The user's email address.
        /// </summary>
        [Output("email")]
        public Output<string> Email { get; private set; } = null!;

        /// <summary>
        /// The user's login password.
        /// </summary>
        [Output("password")]
        public Output<string?> Password { get; private set; } = null!;

        /// <summary>
        /// List of the role IDs that the user has in the tenant
        /// </summary>
        [Output("roleIds")]
        public Output<ImmutableArray<string>> RoleIds { get; private set; } = null!;

        /// <summary>
        /// Skip sending the invite email. If true, user is automatically verified on creation.
        /// </summary>
        [Output("skipInviteEmail")]
        public Output<bool?> SkipInviteEmail { get; private set; } = null!;

        /// <summary>
        /// Whether the user is a super user.
        /// </summary>
        [Output("superuser")]
        public Output<bool?> Superuser { get; private set; } = null!;

        /// <summary>
        /// The tenant ID for this user.
        /// </summary>
        [Output("tenantId")]
        public Output<string> TenantId { get; private set; } = null!;


        /// <summary>
        /// Create a User resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public User(string name, UserArgs args, CustomResourceOptions? options = null)
            : base("frontegg:index/user:User", name, args ?? new UserArgs(), MakeResourceOptions(options, ""))
        {
        }

        private User(string name, Input<string> id, UserState? state = null, CustomResourceOptions? options = null)
            : base("frontegg:index/user:User", name, state, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                AdditionalSecretOutputs =
                {
                    "password",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing User resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="state">Any extra arguments used during the lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static User Get(string name, Input<string> id, UserState? state = null, CustomResourceOptions? options = null)
        {
            return new User(name, id, state, options);
        }
    }

    public sealed class UserArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the user gets verified upon creation.
        /// </summary>
        [Input("automaticallyVerify")]
        public Input<bool>? AutomaticallyVerify { get; set; }

        /// <summary>
        /// The user's email address.
        /// </summary>
        [Input("email", required: true)]
        public Input<string> Email { get; set; } = null!;

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The user's login password.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("roleIds", required: true)]
        private InputList<string>? _roleIds;

        /// <summary>
        /// List of the role IDs that the user has in the tenant
        /// </summary>
        public InputList<string> RoleIds
        {
            get => _roleIds ?? (_roleIds = new InputList<string>());
            set => _roleIds = value;
        }

        /// <summary>
        /// Skip sending the invite email. If true, user is automatically verified on creation.
        /// </summary>
        [Input("skipInviteEmail")]
        public Input<bool>? SkipInviteEmail { get; set; }

        /// <summary>
        /// Whether the user is a super user.
        /// </summary>
        [Input("superuser")]
        public Input<bool>? Superuser { get; set; }

        /// <summary>
        /// The tenant ID for this user.
        /// </summary>
        [Input("tenantId", required: true)]
        public Input<string> TenantId { get; set; } = null!;

        public UserArgs()
        {
        }
        public static new UserArgs Empty => new UserArgs();
    }

    public sealed class UserState : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether the user gets verified upon creation.
        /// </summary>
        [Input("automaticallyVerify")]
        public Input<bool>? AutomaticallyVerify { get; set; }

        /// <summary>
        /// The user's email address.
        /// </summary>
        [Input("email")]
        public Input<string>? Email { get; set; }

        [Input("password")]
        private Input<string>? _password;

        /// <summary>
        /// The user's login password.
        /// </summary>
        public Input<string>? Password
        {
            get => _password;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _password = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        [Input("roleIds")]
        private InputList<string>? _roleIds;

        /// <summary>
        /// List of the role IDs that the user has in the tenant
        /// </summary>
        public InputList<string> RoleIds
        {
            get => _roleIds ?? (_roleIds = new InputList<string>());
            set => _roleIds = value;
        }

        /// <summary>
        /// Skip sending the invite email. If true, user is automatically verified on creation.
        /// </summary>
        [Input("skipInviteEmail")]
        public Input<bool>? SkipInviteEmail { get; set; }

        /// <summary>
        /// Whether the user is a super user.
        /// </summary>
        [Input("superuser")]
        public Input<bool>? Superuser { get; set; }

        /// <summary>
        /// The tenant ID for this user.
        /// </summary>
        [Input("tenantId")]
        public Input<string>? TenantId { get; set; }

        public UserState()
        {
        }
        public static new UserState Empty => new UserState();
    }
}
