// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/nrf110/pulumi-frontegg/sdk/go/frontegg/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// The Frontegg api url. Override to change region. Defaults to EU url.
func GetApiBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "frontegg:apiBaseUrl")
}

// The client ID for a Frontegg portal API key.
func GetClientId(ctx *pulumi.Context) string {
	return config.Get(ctx, "frontegg:clientId")
}

// The client ID from environment settings.
func GetEnvironmentId(ctx *pulumi.Context) string {
	return config.Get(ctx, "frontegg:environmentId")
}

// The Frontegg portal url. Override to change region. Defaults to EU url.
func GetPortalBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "frontegg:portalBaseUrl")
}

// The corresponding secret key for the API key.
func GetSecretKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "frontegg:secretKey")
}
