// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceAdminPortalPaletteError
    {
        /// <summary>
        /// contrast_text color.
        /// </summary>
        public readonly string ContrastText;
        /// <summary>
        /// dark color.
        /// </summary>
        public readonly string Dark;
        /// <summary>
        /// light color.
        /// </summary>
        public readonly string Light;
        /// <summary>
        /// main color.
        /// </summary>
        public readonly string Main;

        [OutputConstructor]
        private WorkspaceAdminPortalPaletteError(
            string contrastText,

            string dark,

            string light,

            string main)
        {
            ContrastText = contrastText;
            Dark = dark;
            Light = light;
            Main = main;
        }
    }
}
