// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceMfaPolicy
    {
        /// <summary>
        /// Allow users to remember their MFA devices.
        /// </summary>
        public readonly bool AllowRememberDevice;
        /// <summary>
        /// The number of seconds that MFA devices can be remembered for, if allow_remember_my_device is true.
        /// </summary>
        public readonly int DeviceExpiration;
        /// <summary>
        /// Whether to force use of MFA.
        /// 
        /// 	Must be one of "off", "on", or "unless-saml".
        /// </summary>
        public readonly string Enforce;

        [OutputConstructor]
        private WorkspaceMfaPolicy(
            bool allowRememberDevice,

            int deviceExpiration,

            string enforce)
        {
            AllowRememberDevice = allowRememberDevice;
            DeviceExpiration = deviceExpiration;
            Enforce = enforce;
        }
    }
}
