// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceSaml
    {
        /// <summary>
        /// The ACS URL for the SAML authentication flow.
        /// </summary>
        public readonly string AcsUrl;
        /// <summary>
        /// The URL to redirect to after the SAML exchange.
        /// </summary>
        public readonly string? RedirectUrl;
        /// <summary>
        /// The name of the service provider that will be displayed to users.
        /// </summary>
        public readonly string SpEntityId;

        [OutputConstructor]
        private WorkspaceSaml(
            string acsUrl,

            string? redirectUrl,

            string spEntityId)
        {
            AcsUrl = acsUrl;
            RedirectUrl = redirectUrl;
            SpEntityId = spEntityId;
        }
    }
}
