// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceMicrosoftSocialLogin
    {
        /// <summary>
        /// The client ID of the Microsoft application to authenticate with. Required when setting **`customised`** parameter to true.
        /// </summary>
        public readonly string? ClientId;
        /// <summary>
        /// Determine whether the SSO should use customized secret and client ID. When passing true, clientId and secret are also required.
        /// </summary>
        public readonly bool? Customised;
        /// <summary>
        /// The URL to redirect to after a successful authentication.
        /// </summary>
        public readonly string RedirectUrl;
        /// <summary>
        /// The secret associated with the Microsoft application. Required when setting **`customised`** parameter to true.
        /// </summary>
        public readonly string? Secret;

        [OutputConstructor]
        private WorkspaceMicrosoftSocialLogin(
            string? clientId,

            bool? customised,

            string redirectUrl,

            string? secret)
        {
            ClientId = clientId;
            Customised = customised;
            RedirectUrl = redirectUrl;
            Secret = secret;
        }
    }
}
