// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceAdminPortalPaletteLoginBox
    {
        /// <summary>
        /// Error color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxError> Errors;
        /// <summary>
        /// Info color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxInfo> Infos;
        /// <summary>
        /// Primary color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxPrimary> Primaries;
        /// <summary>
        /// Secondary color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxSecondary> Secondaries;
        /// <summary>
        /// Success color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxSuccess> Successes;
        /// <summary>
        /// Warning color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxWarning> Warnings;

        [OutputConstructor]
        private WorkspaceAdminPortalPaletteLoginBox(
            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxError> errors,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxInfo> infos,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxPrimary> primaries,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxSecondary> secondaries,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxSuccess> successes,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteLoginBoxWarning> warnings)
        {
            Errors = errors;
            Infos = infos;
            Primaries = primaries;
            Secondaries = secondaries;
            Successes = successes;
            Warnings = warnings;
        }
    }
}
