// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceSsoDomainPolicy
    {
        /// <summary>
        /// Whether to allow users to add their own email domain without validating the domain through DNS.
        /// </summary>
        public readonly bool? AllowVerifiedUsersToAddDomains;
        /// <summary>
        /// Whether to allow users to sign in even via SSO even if the associated domain has not been validated through DNS.
        /// </summary>
        public readonly bool? BypassDomainCrossValidation;
        /// <summary>
        /// Whether to automatically mark new SSO domains as validated, without validating the domain through DNS.
        /// </summary>
        public readonly bool? SkipDomainVerification;

        [OutputConstructor]
        private WorkspaceSsoDomainPolicy(
            bool? allowVerifiedUsersToAddDomains,

            bool? bypassDomainCrossValidation,

            bool? skipDomainVerification)
        {
            AllowVerifiedUsersToAddDomains = allowVerifiedUsersToAddDomains;
            BypassDomainCrossValidation = bypassDomainCrossValidation;
            SkipDomainVerification = skipDomainVerification;
        }
    }
}
