// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceCaptchaPolicy
    {
        /// <summary>
        /// Email addresses that should be exempt from CAPTCHA checks.
        /// </summary>
        public readonly ImmutableArray<string> IgnoredEmails;
        /// <summary>
        /// The minimum CAPTCHA score to accept. Set to 0.0 to accept all scores.
        /// </summary>
        public readonly double MinScore;
        /// <summary>
        /// The reCAPTCHA secret key to use.
        /// </summary>
        public readonly string SecretKey;
        /// <summary>
        /// The reCAPTCHA site key to use.
        /// </summary>
        public readonly string SiteKey;

        [OutputConstructor]
        private WorkspaceCaptchaPolicy(
            ImmutableArray<string> ignoredEmails,

            double minScore,

            string secretKey,

            string siteKey)
        {
            IgnoredEmails = ignoredEmails;
            MinScore = minScore;
            SecretKey = secretKey;
            SiteKey = siteKey;
        }
    }
}
