// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Outputs
{

    [OutputType]
    public sealed class WorkspaceAdminPortalPalette
    {
        /// <summary>
        /// Error color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteError> Errors;
        /// <summary>
        /// Info color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteInfo> Infos;
        /// <summary>
        /// Primary color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPalettePrimary> Primaries;
        /// <summary>
        /// Secondary color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteSecondary> Secondaries;
        /// <summary>
        /// Success color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteSuccess> Successes;
        /// <summary>
        /// Warning color.
        /// </summary>
        public readonly ImmutableArray<Outputs.WorkspaceAdminPortalPaletteWarning> Warnings;

        [OutputConstructor]
        private WorkspaceAdminPortalPalette(
            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteError> errors,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteInfo> infos,

            ImmutableArray<Outputs.WorkspaceAdminPortalPalettePrimary> primaries,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteSecondary> secondaries,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteSuccess> successes,

            ImmutableArray<Outputs.WorkspaceAdminPortalPaletteWarning> warnings)
        {
            Errors = errors;
            Infos = infos;
            Primaries = primaries;
            Secondaries = secondaries;
            Successes = successes;
            Warnings = warnings;
        }
    }
}
