// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package frontegg

import (
	"context"
	"reflect"

	"errors"
	"github.com/nrf110/pulumi-frontegg/sdk/go/frontegg/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The provider type for the frontegg package. By default, resources use package-wide configuration
// settings, however an explicit `Provider` instance may be created and passed during resource
// construction to achieve fine-grained programmatic control over provider settings. See the
// [documentation](https://www.pulumi.com/docs/reference/programming-model/#providers) for more information.
type Provider struct {
	pulumi.ProviderResourceState

	// The Frontegg api url. Override to change region. Defaults to EU url.
	ApiBaseUrl pulumi.StringPtrOutput `pulumi:"apiBaseUrl"`
	// The client ID for a Frontegg portal API key.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// The client ID from environment settings.
	EnvironmentId pulumi.StringPtrOutput `pulumi:"environmentId"`
	// The Frontegg portal url. Override to change region. Defaults to EU url.
	PortalBaseUrl pulumi.StringPtrOutput `pulumi:"portalBaseUrl"`
	// The corresponding secret key for the API key.
	SecretKey pulumi.StringOutput `pulumi:"secretKey"`
}

// NewProvider registers a new resource with the given unique name, arguments, and options.
func NewProvider(ctx *pulumi.Context,
	name string, args *ProviderArgs, opts ...pulumi.ResourceOption) (*Provider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	if args.SecretKey == nil {
		return nil, errors.New("invalid value for required argument 'SecretKey'")
	}
	if args.EnvironmentId != nil {
		args.EnvironmentId = pulumi.ToSecret(args.EnvironmentId).(pulumi.StringPtrInput)
	}
	if args.SecretKey != nil {
		args.SecretKey = pulumi.ToSecret(args.SecretKey).(pulumi.StringInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"environmentId",
		"secretKey",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource Provider
	err := ctx.RegisterResource("pulumi:providers:frontegg", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

type providerArgs struct {
	// The Frontegg api url. Override to change region. Defaults to EU url.
	ApiBaseUrl *string `pulumi:"apiBaseUrl"`
	// The client ID for a Frontegg portal API key.
	ClientId string `pulumi:"clientId"`
	// The client ID from environment settings.
	EnvironmentId *string `pulumi:"environmentId"`
	// The Frontegg portal url. Override to change region. Defaults to EU url.
	PortalBaseUrl *string `pulumi:"portalBaseUrl"`
	// The corresponding secret key for the API key.
	SecretKey string `pulumi:"secretKey"`
}

// The set of arguments for constructing a Provider resource.
type ProviderArgs struct {
	// The Frontegg api url. Override to change region. Defaults to EU url.
	ApiBaseUrl pulumi.StringPtrInput
	// The client ID for a Frontegg portal API key.
	ClientId pulumi.StringInput
	// The client ID from environment settings.
	EnvironmentId pulumi.StringPtrInput
	// The Frontegg portal url. Override to change region. Defaults to EU url.
	PortalBaseUrl pulumi.StringPtrInput
	// The corresponding secret key for the API key.
	SecretKey pulumi.StringInput
}

func (ProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*providerArgs)(nil)).Elem()
}

type ProviderInput interface {
	pulumi.Input

	ToProviderOutput() ProviderOutput
	ToProviderOutputWithContext(ctx context.Context) ProviderOutput
}

func (*Provider) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (i *Provider) ToProviderOutput() ProviderOutput {
	return i.ToProviderOutputWithContext(context.Background())
}

func (i *Provider) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ProviderOutput)
}

type ProviderOutput struct{ *pulumi.OutputState }

func (ProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Provider)(nil)).Elem()
}

func (o ProviderOutput) ToProviderOutput() ProviderOutput {
	return o
}

func (o ProviderOutput) ToProviderOutputWithContext(ctx context.Context) ProviderOutput {
	return o
}

// The Frontegg api url. Override to change region. Defaults to EU url.
func (o ProviderOutput) ApiBaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.ApiBaseUrl }).(pulumi.StringPtrOutput)
}

// The client ID for a Frontegg portal API key.
func (o ProviderOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// The client ID from environment settings.
func (o ProviderOutput) EnvironmentId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.EnvironmentId }).(pulumi.StringPtrOutput)
}

// The Frontegg portal url. Override to change region. Defaults to EU url.
func (o ProviderOutput) PortalBaseUrl() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringPtrOutput { return v.PortalBaseUrl }).(pulumi.StringPtrOutput)
}

// The corresponding secret key for the API key.
func (o ProviderOutput) SecretKey() pulumi.StringOutput {
	return o.ApplyT(func(v *Provider) pulumi.StringOutput { return v.SecretKey }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ProviderInput)(nil)).Elem(), &Provider{})
	pulumi.RegisterOutputType(ProviderOutput{})
}
