// Code generated by the Pulumi Terraform Bridge (tfgen) Tool DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package frontegg

import (
	"context"
	"reflect"

	"errors"
	"github.com/nrf110/pulumi-frontegg/sdk/go/frontegg/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Configures a Frontegg user.
type User struct {
	pulumi.CustomResourceState

	// Whether the user gets verified upon creation.
	AutomaticallyVerify pulumi.BoolPtrOutput `pulumi:"automaticallyVerify"`
	// The user's email address.
	Email pulumi.StringOutput `pulumi:"email"`
	// The user's login password.
	Password pulumi.StringPtrOutput `pulumi:"password"`
	// List of the role IDs that the user has in the tenant
	RoleIds pulumi.StringArrayOutput `pulumi:"roleIds"`
	// Skip sending the invite email. If true, user is automatically verified on creation.
	SkipInviteEmail pulumi.BoolPtrOutput `pulumi:"skipInviteEmail"`
	// Whether the user is a super user.
	Superuser pulumi.BoolPtrOutput `pulumi:"superuser"`
	// The tenant ID for this user.
	TenantId pulumi.StringOutput `pulumi:"tenantId"`
}

// NewUser registers a new resource with the given unique name, arguments, and options.
func NewUser(ctx *pulumi.Context,
	name string, args *UserArgs, opts ...pulumi.ResourceOption) (*User, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Email == nil {
		return nil, errors.New("invalid value for required argument 'Email'")
	}
	if args.RoleIds == nil {
		return nil, errors.New("invalid value for required argument 'RoleIds'")
	}
	if args.TenantId == nil {
		return nil, errors.New("invalid value for required argument 'TenantId'")
	}
	if args.Password != nil {
		args.Password = pulumi.ToSecret(args.Password).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"password",
	})
	opts = append(opts, secrets)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource User
	err := ctx.RegisterResource("frontegg:index/user:User", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetUser gets an existing User resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetUser(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *UserState, opts ...pulumi.ResourceOption) (*User, error) {
	var resource User
	err := ctx.ReadResource("frontegg:index/user:User", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering User resources.
type userState struct {
	// Whether the user gets verified upon creation.
	AutomaticallyVerify *bool `pulumi:"automaticallyVerify"`
	// The user's email address.
	Email *string `pulumi:"email"`
	// The user's login password.
	Password *string `pulumi:"password"`
	// List of the role IDs that the user has in the tenant
	RoleIds []string `pulumi:"roleIds"`
	// Skip sending the invite email. If true, user is automatically verified on creation.
	SkipInviteEmail *bool `pulumi:"skipInviteEmail"`
	// Whether the user is a super user.
	Superuser *bool `pulumi:"superuser"`
	// The tenant ID for this user.
	TenantId *string `pulumi:"tenantId"`
}

type UserState struct {
	// Whether the user gets verified upon creation.
	AutomaticallyVerify pulumi.BoolPtrInput
	// The user's email address.
	Email pulumi.StringPtrInput
	// The user's login password.
	Password pulumi.StringPtrInput
	// List of the role IDs that the user has in the tenant
	RoleIds pulumi.StringArrayInput
	// Skip sending the invite email. If true, user is automatically verified on creation.
	SkipInviteEmail pulumi.BoolPtrInput
	// Whether the user is a super user.
	Superuser pulumi.BoolPtrInput
	// The tenant ID for this user.
	TenantId pulumi.StringPtrInput
}

func (UserState) ElementType() reflect.Type {
	return reflect.TypeOf((*userState)(nil)).Elem()
}

type userArgs struct {
	// Whether the user gets verified upon creation.
	AutomaticallyVerify *bool `pulumi:"automaticallyVerify"`
	// The user's email address.
	Email string `pulumi:"email"`
	// The user's login password.
	Password *string `pulumi:"password"`
	// List of the role IDs that the user has in the tenant
	RoleIds []string `pulumi:"roleIds"`
	// Skip sending the invite email. If true, user is automatically verified on creation.
	SkipInviteEmail *bool `pulumi:"skipInviteEmail"`
	// Whether the user is a super user.
	Superuser *bool `pulumi:"superuser"`
	// The tenant ID for this user.
	TenantId string `pulumi:"tenantId"`
}

// The set of arguments for constructing a User resource.
type UserArgs struct {
	// Whether the user gets verified upon creation.
	AutomaticallyVerify pulumi.BoolPtrInput
	// The user's email address.
	Email pulumi.StringInput
	// The user's login password.
	Password pulumi.StringPtrInput
	// List of the role IDs that the user has in the tenant
	RoleIds pulumi.StringArrayInput
	// Skip sending the invite email. If true, user is automatically verified on creation.
	SkipInviteEmail pulumi.BoolPtrInput
	// Whether the user is a super user.
	Superuser pulumi.BoolPtrInput
	// The tenant ID for this user.
	TenantId pulumi.StringInput
}

func (UserArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*userArgs)(nil)).Elem()
}

type UserInput interface {
	pulumi.Input

	ToUserOutput() UserOutput
	ToUserOutputWithContext(ctx context.Context) UserOutput
}

func (*User) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (i *User) ToUserOutput() UserOutput {
	return i.ToUserOutputWithContext(context.Background())
}

func (i *User) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserOutput)
}

// UserArrayInput is an input type that accepts UserArray and UserArrayOutput values.
// You can construct a concrete instance of `UserArrayInput` via:
//
//	UserArray{ UserArgs{...} }
type UserArrayInput interface {
	pulumi.Input

	ToUserArrayOutput() UserArrayOutput
	ToUserArrayOutputWithContext(context.Context) UserArrayOutput
}

type UserArray []UserInput

func (UserArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (i UserArray) ToUserArrayOutput() UserArrayOutput {
	return i.ToUserArrayOutputWithContext(context.Background())
}

func (i UserArray) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserArrayOutput)
}

// UserMapInput is an input type that accepts UserMap and UserMapOutput values.
// You can construct a concrete instance of `UserMapInput` via:
//
//	UserMap{ "key": UserArgs{...} }
type UserMapInput interface {
	pulumi.Input

	ToUserMapOutput() UserMapOutput
	ToUserMapOutputWithContext(context.Context) UserMapOutput
}

type UserMap map[string]UserInput

func (UserMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (i UserMap) ToUserMapOutput() UserMapOutput {
	return i.ToUserMapOutputWithContext(context.Background())
}

func (i UserMap) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(UserMapOutput)
}

type UserOutput struct{ *pulumi.OutputState }

func (UserOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**User)(nil)).Elem()
}

func (o UserOutput) ToUserOutput() UserOutput {
	return o
}

func (o UserOutput) ToUserOutputWithContext(ctx context.Context) UserOutput {
	return o
}

// Whether the user gets verified upon creation.
func (o UserOutput) AutomaticallyVerify() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.AutomaticallyVerify }).(pulumi.BoolPtrOutput)
}

// The user's email address.
func (o UserOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.Email }).(pulumi.StringOutput)
}

// The user's login password.
func (o UserOutput) Password() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *User) pulumi.StringPtrOutput { return v.Password }).(pulumi.StringPtrOutput)
}

// List of the role IDs that the user has in the tenant
func (o UserOutput) RoleIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *User) pulumi.StringArrayOutput { return v.RoleIds }).(pulumi.StringArrayOutput)
}

// Skip sending the invite email. If true, user is automatically verified on creation.
func (o UserOutput) SkipInviteEmail() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.SkipInviteEmail }).(pulumi.BoolPtrOutput)
}

// Whether the user is a super user.
func (o UserOutput) Superuser() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *User) pulumi.BoolPtrOutput { return v.Superuser }).(pulumi.BoolPtrOutput)
}

// The tenant ID for this user.
func (o UserOutput) TenantId() pulumi.StringOutput {
	return o.ApplyT(func(v *User) pulumi.StringOutput { return v.TenantId }).(pulumi.StringOutput)
}

type UserArrayOutput struct{ *pulumi.OutputState }

func (UserArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*User)(nil)).Elem()
}

func (o UserArrayOutput) ToUserArrayOutput() UserArrayOutput {
	return o
}

func (o UserArrayOutput) ToUserArrayOutputWithContext(ctx context.Context) UserArrayOutput {
	return o
}

func (o UserArrayOutput) Index(i pulumi.IntInput) UserOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *User {
		return vs[0].([]*User)[vs[1].(int)]
	}).(UserOutput)
}

type UserMapOutput struct{ *pulumi.OutputState }

func (UserMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*User)(nil)).Elem()
}

func (o UserMapOutput) ToUserMapOutput() UserMapOutput {
	return o
}

func (o UserMapOutput) ToUserMapOutputWithContext(ctx context.Context) UserMapOutput {
	return o
}

func (o UserMapOutput) MapIndex(k pulumi.StringInput) UserOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *User {
		return vs[0].(map[string]*User)[vs[1].(string)]
	}).(UserOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*UserInput)(nil)).Elem(), &User{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserArrayInput)(nil)).Elem(), UserArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*UserMapInput)(nil)).Elem(), UserMap{})
	pulumi.RegisterOutputType(UserOutput{})
	pulumi.RegisterOutputType(UserArrayOutput{})
	pulumi.RegisterOutputType(UserMapOutput{})
}
