// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceCaptchaPolicyArgs : global::Pulumi.ResourceArgs
    {
        [Input("ignoredEmails")]
        private InputList<string>? _ignoredEmails;

        /// <summary>
        /// Email addresses that should be exempt from CAPTCHA checks.
        /// </summary>
        public InputList<string> IgnoredEmails
        {
            get => _ignoredEmails ?? (_ignoredEmails = new InputList<string>());
            set => _ignoredEmails = value;
        }

        /// <summary>
        /// The minimum CAPTCHA score to accept. Set to 0.0 to accept all scores.
        /// </summary>
        [Input("minScore", required: true)]
        public Input<double> MinScore { get; set; } = null!;

        /// <summary>
        /// The reCAPTCHA secret key to use.
        /// </summary>
        [Input("secretKey", required: true)]
        public Input<string> SecretKey { get; set; } = null!;

        /// <summary>
        /// The reCAPTCHA site key to use.
        /// </summary>
        [Input("siteKey", required: true)]
        public Input<string> SiteKey { get; set; } = null!;

        public WorkspaceCaptchaPolicyArgs()
        {
        }
        public static new WorkspaceCaptchaPolicyArgs Empty => new WorkspaceCaptchaPolicyArgs();
    }
}
