// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceSamlGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ACS URL for the SAML authentication flow.
        /// </summary>
        [Input("acsUrl", required: true)]
        public Input<string> AcsUrl { get; set; } = null!;

        /// <summary>
        /// The URL to redirect to after the SAML exchange.
        /// </summary>
        [Input("redirectUrl")]
        public Input<string>? RedirectUrl { get; set; }

        /// <summary>
        /// The name of the service provider that will be displayed to users.
        /// </summary>
        [Input("spEntityId", required: true)]
        public Input<string> SpEntityId { get; set; } = null!;

        public WorkspaceSamlGetArgs()
        {
        }
        public static new WorkspaceSamlGetArgs Empty => new WorkspaceSamlGetArgs();
    }
}
