// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceMfaPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Allow users to remember their MFA devices.
        /// </summary>
        [Input("allowRememberDevice", required: true)]
        public Input<bool> AllowRememberDevice { get; set; } = null!;

        /// <summary>
        /// The number of seconds that MFA devices can be remembered for, if allow_remember_my_device is true.
        /// </summary>
        [Input("deviceExpiration", required: true)]
        public Input<int> DeviceExpiration { get; set; } = null!;

        /// <summary>
        /// Whether to force use of MFA.
        /// 
        /// 	Must be one of "off", "on", or "unless-saml".
        /// </summary>
        [Input("enforce", required: true)]
        public Input<string> Enforce { get; set; } = null!;

        public WorkspaceMfaPolicyGetArgs()
        {
        }
        public static new WorkspaceMfaPolicyGetArgs Empty => new WorkspaceMfaPolicyGetArgs();
    }
}
