// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceAdminPortalPaletteLoginBoxGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("errors")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxErrorGetArgs>? _errors;

        /// <summary>
        /// Error color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxErrorGetArgs> Errors
        {
            get => _errors ?? (_errors = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxErrorGetArgs>());
            set => _errors = value;
        }

        [Input("infos")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxInfoGetArgs>? _infos;

        /// <summary>
        /// Info color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxInfoGetArgs> Infos
        {
            get => _infos ?? (_infos = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxInfoGetArgs>());
            set => _infos = value;
        }

        [Input("primaries")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxPrimaryGetArgs>? _primaries;

        /// <summary>
        /// Primary color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxPrimaryGetArgs> Primaries
        {
            get => _primaries ?? (_primaries = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxPrimaryGetArgs>());
            set => _primaries = value;
        }

        [Input("secondaries")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSecondaryGetArgs>? _secondaries;

        /// <summary>
        /// Secondary color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSecondaryGetArgs> Secondaries
        {
            get => _secondaries ?? (_secondaries = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSecondaryGetArgs>());
            set => _secondaries = value;
        }

        [Input("successes")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSuccessGetArgs>? _successes;

        /// <summary>
        /// Success color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSuccessGetArgs> Successes
        {
            get => _successes ?? (_successes = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSuccessGetArgs>());
            set => _successes = value;
        }

        [Input("warnings")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxWarningGetArgs>? _warnings;

        /// <summary>
        /// Warning color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxWarningGetArgs> Warnings
        {
            get => _warnings ?? (_warnings = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxWarningGetArgs>());
            set => _warnings = value;
        }

        public WorkspaceAdminPortalPaletteLoginBoxGetArgs()
        {
        }
        public static new WorkspaceAdminPortalPaletteLoginBoxGetArgs Empty => new WorkspaceAdminPortalPaletteLoginBoxGetArgs();
    }
}
