// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceSsoMultiTenantPolicyArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Strategy for logging in nonexisting users that match SSO configurations for multiple tenants when no tenant has been specified. Either BLOCK or FIRST_CREATED.
        /// </summary>
        [Input("unspecifiedTenantStrategy")]
        public Input<string>? UnspecifiedTenantStrategy { get; set; }

        /// <summary>
        /// Whether users with existing accounts that match SSO configurations for multiple tenants should be logged in using the SSO for their active (last logged into) account, or whether the unspecified tenant strategy should apply.
        /// </summary>
        [Input("useActiveTenant")]
        public Input<bool>? UseActiveTenant { get; set; }

        public WorkspaceSsoMultiTenantPolicyArgs()
        {
        }
        public static new WorkspaceSsoMultiTenantPolicyArgs Empty => new WorkspaceSsoMultiTenantPolicyArgs();
    }
}
