// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceAdminPortalPaletteLoginBoxArgs : global::Pulumi.ResourceArgs
    {
        [Input("errors")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxErrorArgs>? _errors;

        /// <summary>
        /// Error color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxErrorArgs> Errors
        {
            get => _errors ?? (_errors = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxErrorArgs>());
            set => _errors = value;
        }

        [Input("infos")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxInfoArgs>? _infos;

        /// <summary>
        /// Info color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxInfoArgs> Infos
        {
            get => _infos ?? (_infos = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxInfoArgs>());
            set => _infos = value;
        }

        [Input("primaries")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxPrimaryArgs>? _primaries;

        /// <summary>
        /// Primary color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxPrimaryArgs> Primaries
        {
            get => _primaries ?? (_primaries = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxPrimaryArgs>());
            set => _primaries = value;
        }

        [Input("secondaries")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSecondaryArgs>? _secondaries;

        /// <summary>
        /// Secondary color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSecondaryArgs> Secondaries
        {
            get => _secondaries ?? (_secondaries = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSecondaryArgs>());
            set => _secondaries = value;
        }

        [Input("successes")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSuccessArgs>? _successes;

        /// <summary>
        /// Success color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSuccessArgs> Successes
        {
            get => _successes ?? (_successes = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxSuccessArgs>());
            set => _successes = value;
        }

        [Input("warnings")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxWarningArgs>? _warnings;

        /// <summary>
        /// Warning color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxWarningArgs> Warnings
        {
            get => _warnings ?? (_warnings = new InputList<Inputs.WorkspaceAdminPortalPaletteLoginBoxWarningArgs>());
            set => _warnings = value;
        }

        public WorkspaceAdminPortalPaletteLoginBoxArgs()
        {
        }
        public static new WorkspaceAdminPortalPaletteLoginBoxArgs Empty => new WorkspaceAdminPortalPaletteLoginBoxArgs();
    }
}
