// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceAdminPortalPaletteAdminPortalArgs : global::Pulumi.ResourceArgs
    {
        [Input("errors")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalErrorArgs>? _errors;

        /// <summary>
        /// Error color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalErrorArgs> Errors
        {
            get => _errors ?? (_errors = new InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalErrorArgs>());
            set => _errors = value;
        }

        [Input("infos")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalInfoArgs>? _infos;

        /// <summary>
        /// Info color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalInfoArgs> Infos
        {
            get => _infos ?? (_infos = new InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalInfoArgs>());
            set => _infos = value;
        }

        [Input("primaries")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalPrimaryArgs>? _primaries;

        /// <summary>
        /// Primary color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalPrimaryArgs> Primaries
        {
            get => _primaries ?? (_primaries = new InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalPrimaryArgs>());
            set => _primaries = value;
        }

        [Input("secondaries")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalSecondaryArgs>? _secondaries;

        /// <summary>
        /// Secondary color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalSecondaryArgs> Secondaries
        {
            get => _secondaries ?? (_secondaries = new InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalSecondaryArgs>());
            set => _secondaries = value;
        }

        [Input("successes")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalSuccessArgs>? _successes;

        /// <summary>
        /// Success color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalSuccessArgs> Successes
        {
            get => _successes ?? (_successes = new InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalSuccessArgs>());
            set => _successes = value;
        }

        [Input("warnings")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalWarningArgs>? _warnings;

        /// <summary>
        /// Warning color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalWarningArgs> Warnings
        {
            get => _warnings ?? (_warnings = new InputList<Inputs.WorkspaceAdminPortalPaletteAdminPortalWarningArgs>());
            set => _warnings = value;
        }

        public WorkspaceAdminPortalPaletteAdminPortalArgs()
        {
        }
        public static new WorkspaceAdminPortalPaletteAdminPortalArgs Empty => new WorkspaceAdminPortalPaletteAdminPortalArgs();
    }
}
