// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceLockoutPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The number of failed attempts after which a user will be locked out.
        /// </summary>
        [Input("maxAttempts", required: true)]
        public Input<int> MaxAttempts { get; set; } = null!;

        public WorkspaceLockoutPolicyGetArgs()
        {
        }
        public static new WorkspaceLockoutPolicyGetArgs Empty => new WorkspaceLockoutPolicyGetArgs();
    }
}
