// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceAdminPortalPaletteGetArgs : global::Pulumi.ResourceArgs
    {
        [Input("errors")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteErrorGetArgs>? _errors;

        /// <summary>
        /// Error color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteErrorGetArgs> Errors
        {
            get => _errors ?? (_errors = new InputList<Inputs.WorkspaceAdminPortalPaletteErrorGetArgs>());
            set => _errors = value;
        }

        [Input("infos")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteInfoGetArgs>? _infos;

        /// <summary>
        /// Info color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteInfoGetArgs> Infos
        {
            get => _infos ?? (_infos = new InputList<Inputs.WorkspaceAdminPortalPaletteInfoGetArgs>());
            set => _infos = value;
        }

        [Input("primaries")]
        private InputList<Inputs.WorkspaceAdminPortalPalettePrimaryGetArgs>? _primaries;

        /// <summary>
        /// Primary color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPalettePrimaryGetArgs> Primaries
        {
            get => _primaries ?? (_primaries = new InputList<Inputs.WorkspaceAdminPortalPalettePrimaryGetArgs>());
            set => _primaries = value;
        }

        [Input("secondaries")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteSecondaryGetArgs>? _secondaries;

        /// <summary>
        /// Secondary color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteSecondaryGetArgs> Secondaries
        {
            get => _secondaries ?? (_secondaries = new InputList<Inputs.WorkspaceAdminPortalPaletteSecondaryGetArgs>());
            set => _secondaries = value;
        }

        [Input("successes")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteSuccessGetArgs>? _successes;

        /// <summary>
        /// Success color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteSuccessGetArgs> Successes
        {
            get => _successes ?? (_successes = new InputList<Inputs.WorkspaceAdminPortalPaletteSuccessGetArgs>());
            set => _successes = value;
        }

        [Input("warnings")]
        private InputList<Inputs.WorkspaceAdminPortalPaletteWarningGetArgs>? _warnings;

        /// <summary>
        /// Warning color.
        /// </summary>
        public InputList<Inputs.WorkspaceAdminPortalPaletteWarningGetArgs> Warnings
        {
            get => _warnings ?? (_warnings = new InputList<Inputs.WorkspaceAdminPortalPaletteWarningGetArgs>());
            set => _warnings = value;
        }

        public WorkspaceAdminPortalPaletteGetArgs()
        {
        }
        public static new WorkspaceAdminPortalPaletteGetArgs Empty => new WorkspaceAdminPortalPaletteGetArgs();
    }
}
