// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceOidcArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The URL to redirect to after the OIDC exchange.
        /// </summary>
        [Input("redirectUrl", required: true)]
        public Input<string> RedirectUrl { get; set; } = null!;

        public WorkspaceOidcArgs()
        {
        }
        public static new WorkspaceOidcArgs Empty => new WorkspaceOidcArgs();
    }
}
