// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceGoogleSocialLoginArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The client ID of the Google application to authenticate with. Required when setting **`customised`** parameter to true.
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// Determine whether the SSO should use customized secret and client ID. When passing true, clientId and secret are also required.
        /// </summary>
        [Input("customised")]
        public Input<bool>? Customised { get; set; }

        /// <summary>
        /// The URL to redirect to after a successful authentication.
        /// </summary>
        [Input("redirectUrl", required: true)]
        public Input<string> RedirectUrl { get; set; } = null!;

        [Input("secret")]
        private Input<string>? _secret;

        /// <summary>
        /// The secret associated with the Google application. Required when setting **`customised`** parameter to true.
        /// </summary>
        public Input<string>? Secret
        {
            get => _secret;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _secret = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public WorkspaceGoogleSocialLoginArgs()
        {
        }
        public static new WorkspaceGoogleSocialLoginArgs Empty => new WorkspaceGoogleSocialLoginArgs();
    }
}
