// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceSsoDomainPolicyGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Whether to allow users to add their own email domain without validating the domain through DNS.
        /// </summary>
        [Input("allowVerifiedUsersToAddDomains")]
        public Input<bool>? AllowVerifiedUsersToAddDomains { get; set; }

        /// <summary>
        /// Whether to allow users to sign in even via SSO even if the associated domain has not been validated through DNS.
        /// </summary>
        [Input("bypassDomainCrossValidation")]
        public Input<bool>? BypassDomainCrossValidation { get; set; }

        /// <summary>
        /// Whether to automatically mark new SSO domains as validated, without validating the domain through DNS.
        /// </summary>
        [Input("skipDomainVerification")]
        public Input<bool>? SkipDomainVerification { get; set; }

        public WorkspaceSsoDomainPolicyGetArgs()
        {
        }
        public static new WorkspaceSsoDomainPolicyGetArgs Empty => new WorkspaceSsoDomainPolicyGetArgs();
    }
}
