// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Frontegg.Inputs
{

    public sealed class WorkspaceAdminPortalGetArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Enable access to account settings in the admin portal.
        /// </summary>
        [Input("enableAccountSettings", required: true)]
        public Input<bool> EnableAccountSettings { get; set; } = null!;

        /// <summary>
        /// Enable access to API tokens in the admin portal.
        /// </summary>
        [Input("enableApiTokens", required: true)]
        public Input<bool> EnableApiTokens { get; set; } = null!;

        /// <summary>
        /// Enable access to audit logs in the admin portal.
        /// </summary>
        [Input("enableAuditLogs", required: true)]
        public Input<bool> EnableAuditLogs { get; set; } = null!;

        /// <summary>
        /// Enable access to groups in the admin portal.
        /// </summary>
        [Input("enableGroups", required: true)]
        public Input<bool> EnableGroups { get; set; } = null!;

        /// <summary>
        /// Enable access to personal API tokens in the admin portal.
        /// </summary>
        [Input("enablePersonalApiTokens", required: true)]
        public Input<bool> EnablePersonalApiTokens { get; set; } = null!;

        /// <summary>
        /// Enable access to privacy settings in the admin portal.
        /// </summary>
        [Input("enablePrivacy", required: true)]
        public Input<bool> EnablePrivacy { get; set; } = null!;

        /// <summary>
        /// Enable access to profile settings in the admin portal.
        /// </summary>
        [Input("enableProfile", required: true)]
        public Input<bool> EnableProfile { get; set; } = null!;

        /// <summary>
        /// Enable access to provisioning settings in the admin portal.
        /// </summary>
        [Input("enableProvisioning", required: true)]
        public Input<bool> EnableProvisioning { get; set; } = null!;

        /// <summary>
        /// Enable access to roles and permissions in the admin portal.
        /// </summary>
        [Input("enableRoles", required: true)]
        public Input<bool> EnableRoles { get; set; } = null!;

        /// <summary>
        /// Enable access to security settings in the admin portal.
        /// </summary>
        [Input("enableSecurity", required: true)]
        public Input<bool> EnableSecurity { get; set; } = null!;

        /// <summary>
        /// Enable access to SSO settings in the admin portal.
        /// </summary>
        [Input("enableSso", required: true)]
        public Input<bool> EnableSso { get; set; } = null!;

        /// <summary>
        /// Enable access to subscription settings in the admin portal.
        /// </summary>
        [Input("enableSubscriptions", required: true)]
        public Input<bool> EnableSubscriptions { get; set; } = null!;

        /// <summary>
        /// Enable access to usage information in the admin portal.
        /// </summary>
        [Input("enableUsage", required: true)]
        public Input<bool> EnableUsage { get; set; } = null!;

        /// <summary>
        /// Enable access to user management in the admin portal.
        /// </summary>
        [Input("enableUsers", required: true)]
        public Input<bool> EnableUsers { get; set; } = null!;

        /// <summary>
        /// Enable access to webhooks in the admin portal.
        /// </summary>
        [Input("enableWebhooks", required: true)]
        public Input<bool> EnableWebhooks { get; set; } = null!;

        /// <summary>
        /// Configures the color palette for the admin portal.
        /// </summary>
        [Input("palette")]
        public Input<Inputs.WorkspaceAdminPortalPaletteGetArgs>? Palette { get; set; }

        /// <summary>
        /// Configures the color palette for the admin portal.
        /// </summary>
        [Input("paletteAdminPortal")]
        public Input<Inputs.WorkspaceAdminPortalPaletteAdminPortalGetArgs>? PaletteAdminPortal { get; set; }

        /// <summary>
        /// Configures the color palette for the admin portal.
        /// </summary>
        [Input("paletteLoginBox")]
        public Input<Inputs.WorkspaceAdminPortalPaletteLoginBoxGetArgs>? PaletteLoginBox { get; set; }

        public WorkspaceAdminPortalGetArgs()
        {
        }
        public static new WorkspaceAdminPortalGetArgs Empty => new WorkspaceAdminPortalGetArgs();
    }
}
